### ISSUE TITLE
Branch 6.0: can't compile under Windows 10

### ISSUE THREAD

**Issue by nguyenpham** [sjemens/qsqlcipher-qt5#16]
I have compiled well branch 6.0 under macOS. However, I can't do that under Windows 10 with Qt 6.4 (MSVC2019 64bit).

Below is the error when I compile it with the command prompt:

```
C:\Users\nguyenpham\qsqlcipher-qt5\build>qmake ..\qsqlcipher.pro
Info: creating stash file C:\Users\nguyenpham\qsqlcipher-qt5\build\.qmake.stash

C:\Users\nguyenpham\qsqlcipher-qt5\build>make
cd qsqlcipher\ && ( if not exist Makefile C:\Qt\6.4.0\msvc2019_64\bin\qmake.exe -o Makefile C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher\qsqlcipher.pro ) && make -f Makefile
Info: creating stash file C:\Users\nguyenpham\qsqlcipher-qt5\build\qsqlcipher\.qmake.stash
make[1]: Entering directory `C:/Users/nguyenpham/qsqlcipher-qt5/build/qsqlcipher'
make -f Makefile.Release
make[2]: Entering directory `C:/Users/nguyenpham/qsqlcipher-qt5/build/qsqlcipher'
Makefile.Release:77: *** missing separator.  Stop.
make[2]: Leaving directory `C:/Users/nguyenpham/qsqlcipher-qt5/build/qsqlcipher'
make[1]: *** [release] Error 2
make[1]: Leaving directory `C:/Users/nguyenpham/qsqlcipher-qt5/build/qsqlcipher'
make: *** [sub-qsqlcipher-make_first] Error 2

```

My 2nd attempt is to use Qt Creator. I have loaded the project, do "qmake" then "build". It worked fine with branch 5.15 (using Qt 5.15). However, it can't work with branch 6.0 (using Qt 6.4, MSVC2019 64bit). Below is the error message (about ```'lld-link' is not recognized as an internal or external command```). Any idea how to fix it?

```
08:48:55: Running steps for project qsqlcipher...
08:48:55: Configuration unchanged, skipping qmake step.
08:48:55: Starting: "C:\Qt\Tools\QtCreator\bin\jom.exe" 
	cd qsqlcipher\ && ( if not exist Makefile C:\Qt\6.4.0\msvc2019_64\bin\qmake.exe -o Makefile C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher\qsqlcipher.pro -spec win32-clang-msvc "CONFIG+=qtquickcompiler" ) && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
	cd C:/Users/nguyenpham/qsqlcipher-qt5/qsqlcipher/../3rdparty/libtomcrypt && nmake -f makefile.msvc CFLAGS=/Ox
	clang-cl -BxC:\Qt\6.4.0\msvc2019_64\bin\qmake.exe -nologo -Zc:wchar_t -Wno-microsoft-enum-value -fms-compatibility-version=19.29.30145 -O2 -Zi -MD -std:c++17 -utf-8 -W3 -w34100 -w34189 -w44996 -E C:\Qt\6.4.0\msvc2019_64\mkspecs\features\data\dummy.cpp 2>NUL >.moc\release\moc_predefs.h
	rc /NOLOGO -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL -fo .obj\release\qsqlcipher_resource.res qsqlcipher_resource.rc
	clang-cl -c -nologo -Zc:wchar_t -Wno-microsoft-enum-value -fms-compatibility-version=19.29.30145 -O2 -Zi -MD -std:c++17 -utf-8 -W3 -w34100 -w34189 -w44996 /Fd.obj\release\qsqlcipher.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL -IC:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher -I. -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\sqlcipher -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\libtomcrypt\src\headers -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0\QtCore -IC:\Qt\6.4.0\msvc2019_64\include -IC:\Qt\6.4.0\msvc2019_64\include\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore -I.moc\release -IC:\Qt\6.4.0\msvc2019_64\mkspecs\win32-clang-msvc -Fo.obj\release\ @C:\Users\NGUYEN~1\AppData\Local\Temp\qsql_sqlite.obj.4928.0.jom
	C:\Qt\6.4.0\msvc2019_64\bin\moc.exe -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL --compiler-flavor=msvc --include C:/Users/nguyenpham/build-qsqlcipher-Desktop_Qt_6_4_0_MSVC2019_64bit-Release/qsqlcipher/.moc/release/moc_predefs.h -IC:/Qt/6.4.0/msvc2019_64/mkspecs/win32-clang-msvc -IC:/Users/nguyenpham/qsqlcipher-qt5/qsqlcipher -IC:/Users/nguyenpham/qsqlcipher-qt5/3rdparty/sqlcipher -IC:/Users/nguyenpham/qsqlcipher-qt5/3rdparty/libtomcrypt/src/headers -IC:/Qt/6.4.0/msvc2019_64/include/QtSql/6.4.0 -IC:/Qt/6.4.0/msvc2019_64/include/QtSql/6.4.0/QtSql -IC:/Qt/6.4.0/msvc2019_64/include/QtCore/6.4.0 -IC:/Qt/6.4.0/msvc2019_64/include/QtCore/6.4.0/QtCore -IC:/Qt/6.4.0/msvc2019_64/include -IC:/Qt/6.4.0/msvc2019_64/include/QtSql -IC:/Qt/6.4.0/msvc2019_64/include/QtCore -I. -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher\smain.cpp -o .moc\release\smain.moc
	clang-cl -c -nologo -Zc:wchar_t -Wno-microsoft-enum-value -fms-compatibility-version=19.29.30145 -O2 -Zi -MD -utf-8 -w /Fd.obj\release\qsqlcipher.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL -IC:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher -I. -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\sqlcipher -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\libtomcrypt\src\headers -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0\QtCore -IC:\Qt\6.4.0\msvc2019_64\include -IC:\Qt\6.4.0\msvc2019_64\include\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore -I.moc\release -IC:\Qt\6.4.0\msvc2019_64\mkspecs\win32-clang-msvc -Fo.obj\release\ @C:\Users\NGUYEN~1\AppData\Local\Temp\sqlite3.obj.4928.15.jom
	C:\Qt\6.4.0\msvc2019_64\bin\moc.exe -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL --compiler-flavor=msvc --include C:/Users/nguyenpham/build-qsqlcipher-Desktop_Qt_6_4_0_MSVC2019_64bit-Release/qsqlcipher/.moc/release/moc_predefs.h -IC:/Qt/6.4.0/msvc2019_64/mkspecs/win32-clang-msvc -IC:/Users/nguyenpham/qsqlcipher-qt5/qsqlcipher -IC:/Users/nguyenpham/qsqlcipher-qt5/3rdparty/sqlcipher -IC:/Users/nguyenpham/qsqlcipher-qt5/3rdparty/libtomcrypt/src/headers -IC:/Qt/6.4.0/msvc2019_64/include/QtSql/6.4.0 -IC:/Qt/6.4.0/msvc2019_64/include/QtSql/6.4.0/QtSql -IC:/Qt/6.4.0/msvc2019_64/include/QtCore/6.4.0 -IC:/Qt/6.4.0/msvc2019_64/include/QtCore/6.4.0/QtCore -IC:/Qt/6.4.0/msvc2019_64/include -IC:/Qt/6.4.0/msvc2019_64/include/QtSql -IC:/Qt/6.4.0/msvc2019_64/include/QtCore -I. -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher\qsql_sqlite_p.h -o .moc\release\moc_qsql_sqlite_p.cpp
	clang-cl -c -nologo -Zc:wchar_t -Wno-microsoft-enum-value -fms-compatibility-version=19.29.30145 -O2 -Zi -MD -std:c++17 -utf-8 -W3 -w34100 -w34189 -w44996 /Fd.obj\release\qsqlcipher.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL -IC:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher -I. -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\sqlcipher -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\libtomcrypt\src\headers -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0\QtCore -IC:\Qt\6.4.0\msvc2019_64\include -IC:\Qt\6.4.0\msvc2019_64\include\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore -I.moc\release -IC:\Qt\6.4.0\msvc2019_64\mkspecs\win32-clang-msvc -Fo.obj\release\ @C:\Users\NGUYEN~1\AppData\Local\Temp\moc_qsql_sqlite_p.obj.4928.390.jom
In file included from C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher\qsql_sqlite.cpp:40:
In file included from C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher/qsql_sqlite_p.h:54:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtSql/qsqldriver.h:7:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtSql/qtsqlglobal.h:7:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtCore/qglobal.h:1406:
C:\Qt\6.4.0\msvc2019_64\include\QtCore/qversiontagging.h(90,13): warning: known but unsupported action 'shared' for '#pragma section' - ignored [-Wignored-pragmas]
#    pragma section(".qtversion",read,shared)
            ^
In file included from .moc\release\moc_qsql_sqlite_p.cpp:10:
In file included from .moc\release/../../../../qsqlcipher-qt5/qsqlcipher/qsql_sqlite_p.h:54:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtSql/qsqldriver.h:7:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtSql/qtsqlglobal.h:7:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtCore/qglobal.h:1406:
C:\Qt\6.4.0\msvc2019_64\include\QtCore/qversiontagging.h(90,13): warning: known but unsupported action 'shared' for '#pragma section' - ignored [-Wignored-pragmas]
#    pragma section(".qtversion",read,shared)
            ^
1 warning generated.
	clang-cl -c -nologo -Zc:wchar_t -Wno-microsoft-enum-value -fms-compatibility-version=19.29.30145 -O2 -Zi -MD -std:c++17 -utf-8 -W3 -w34100 -w34189 -w44996 /Fd.obj\release\qsqlcipher.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_JAVA_STYLE_ITERATORS -DNDEBUG -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_LIBTOMCRYPT -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SESSION -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL -IC:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher -I. -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\sqlcipher -IC:\Users\nguyenpham\qsqlcipher-qt5\3rdparty\libtomcrypt\src\headers -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtSql\6.4.0\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0 -IC:\Qt\6.4.0\msvc2019_64\include\QtCore\6.4.0\QtCore -IC:\Qt\6.4.0\msvc2019_64\include -IC:\Qt\6.4.0\msvc2019_64\include\QtSql -IC:\Qt\6.4.0\msvc2019_64\include\QtCore -I.moc\release -IC:\Qt\6.4.0\msvc2019_64\mkspecs\win32-clang-msvc -Fo.obj\release\ @C:\Users\NGUYEN~1\AppData\Local\Temp\smain.obj.4928.453.jom
In file included from C:\Users\nguyenpham\qsqlcipher-qt5\qsqlcipher\smain.cpp:40:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtSql\qsqldriverplugin.h:7:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtSql/qtsqlglobal.h:7:
In file included from C:\Qt\6.4.0\msvc2019_64\include\QtCore/qglobal.h:1406:
C:\Qt\6.4.0\msvc2019_64\include\QtCore/qversiontagging.h(90,13): warning: known but unsupported action 'shared' for '#pragma section' - ignored [-Wignored-pragmas]
#    pragma section(".qtversion",read,shared)
            ^
1 warning generated.
1 warning generated.
	lld-link /NOLOGO /DYNAMICBASE /NXCOMPAT /OPT:REF /OPT:ICF /INCREMENTAL:NO /DEBUG /DLL /SUBSYSTEM:WINDOWS /NODEFAULTLIB:LIBCMT /VERSION:6.4 /MANIFEST:embed /OUT:plugins\sqldrivers\qsqlcipher.dll @C:\Users\NGUYEN~1\AppData\Local\Temp\qsqlcipher.dll.4928.47187.jom
'lld-link' is not recognized as an internal or external command,
operable program or batch file.
jom: C:\Users\nguyenpham\build-qsqlcipher-Desktop_Qt_6_4_0_MSVC2019_64bit-Release\qsqlcipher\Makefile.Release [plugins\sqldrivers\qsqlcipher.dll] Error 1
jom: C:\Users\nguyenpham\build-qsqlcipher-Desktop_Qt_6_4_0_MSVC2019_64bit-Release\qsqlcipher\Makefile [release] Error 2
jom: C:\Users\nguyenpham\build-qsqlcipher-Desktop_Qt_6_4_0_MSVC2019_64bit-Release\Makefile [sub-qsqlcipher-make_first] Error 2
08:49:43: The process "C:\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project qsqlcipher (kit: Desktop Qt 6.4.0 MSVC2019 64bit)
When executing step "Make"
08:49:43: Elapsed time: 00:47.

```

**Comment by sjemens** [comment]
'ldd-link' error suggests that something is not setup right with your kit in qtcreator. You should double check your settings there. 
 
Btw I have just pushed a new 6.4 branch which is in sync with qsqlite from qtbase 6.4 for you to try.

**Comment by nguyenpham** [comment]
Thanks a lot for your effort and for the new version.

I still have problems when compiling from the command line (same errors).

For using Qt Creator, firstly I have the same error. It is surprising because I could compile 5.15 without any problem.

After searching for a while, I realise Qt Creator picked up wrongly the compiler even though it displayed using MSVC2019. After selecting the right compiler (MSVC2019), I can compile your library successfully.

You may add some notes about using Qt Creator for compiling (load the project by Qt Creator, run qmake then build). I think it is a bit easier for beginners since it is more visually than using the command line/terminal.

Thanks again.
